name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.bump.outputs.bumped }}
      changed-files: ${{ steps.bump.outputs.changed-files }}
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - uses: prantlf/bump-version-action@v2
      id: bump
      with:
        bump-files: src/jsonlint.v
    - uses: prantlf/shelve-changes-action@v2
    - run: make RELEASE=1
    - if: ${{ steps.bump.outputs.bumped == 'true' }}
      uses: prantlf/shelve-output-action@v3
      with:
        extra: man

  linux-arm:
    if: ${{ github.ref_name == 'master' && needs.linux.outputs.changed == 'true' }}
    needs:
      - linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - uses: prantlf/unshelve-changes-action@v2
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        files: ${{ needs.linux.outputs.changed-files }}
        discard-shelf: false
    - run: |
        sudo apt-get update
        sudo apt-get install gcc gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - run: make build RELEASE=1 LINUX_ARM=1
    - if: ${{ needs.linux.outputs.changed == 'true' }}
      uses: prantlf/shelve-output-action@v3
      with:
        arch: arm64
        extra: man

  linux-riscv:
    if: ${{ github.ref_name == 'master' && needs.linux.outputs.changed == 'true' }}
    needs:
      - linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - uses: prantlf/unshelve-changes-action@v2
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        files: ${{ needs.linux.outputs.changed-files }}
        discard-shelf: false
    - run: |
        sudo apt-get update
        sudo apt-get install gcc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu
    - run: make build RELEASE=1 LINUX_RISCV=1
    - uses: prantlf/shelve-output-action@v3
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        arch: riscv64
        extra: man

  macos:
    needs:
      - linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - if: ${{ needs.linux.outputs.changed == 'true' }}
      uses: prantlf/unshelve-changes-action@v2
      with:
        files: ${{ needs.linux.outputs.changed-files }}
        discard-shelf: false
    - run: make RELEASE=1
    - if: ${{ needs.linux.outputs.changed == 'true' }}
      uses: prantlf/shelve-output-action@v3
      with:
        extra: man

  macos-arm:
    if: ${{ github.ref_name == 'master' && needs.linux.outputs.changed == 'true' }}
    needs:
      - linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - uses: prantlf/unshelve-changes-action@v2
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        files: ${{ needs.linux.outputs.changed-files }}
        discard-shelf: false
    - run: make build RELEASE=1 MACOS_ARM=1
    - uses: prantlf/shelve-output-action@v3
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        arch: arm64
        extra: man

  windows-cross:
    needs:
      - linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - uses: prantlf/unshelve-changes-action@v2
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        files: ${{ needs.linux.outputs.changed-files }}
        discard-shelf: false
    - run: sudo apt-get install gcc-mingw-w64-x86-64
    - run: make build RELEASE=1 WINDOWS=1
    - uses: prantlf/shelve-output-action@v3
      if: ${{ needs.linux.outputs.changed == 'true' }}
      with:
        os: windows

  # windows:
  #   needs:
  #     - linux
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Sources
  #     uses: actions/checkout@v4
  #   - name: Setup V
  #     uses: prantlf/setup-v-action@v2
  #   - name: Unshelve changes
  #     if: ${{ needs.linux.outputs.changed == 'true' }}
  #     uses: prantlf/unshelve-changes-action@v2
  #     with:
  #       files: ${{ needs.linux.outputs.changed-files }}
  #       discard-shelf: false
  #   - name: Install Cross-Compiler
  #     run: sudo apt-get install gcc-mingw-w64-x86-64
  #   - name: Build Windows
  #     run: make build RELEASE=1 WINDOWS=1
  #   - name: Shelve output
  #     if: ${{ needs.linux.outputs.changed == 'true' }}
  #     uses: prantlf/shelve-output-action@v3
  #     with:
  #       os: windows

  # windows:
  #   needs:
  #     - linux
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout Sources
  #     uses: actions/checkout@v4
  #   - name: Setup V
  #     uses: prantlf/setup-v-action@v2
  #   - name: Unshelve changes
  #     if: ${{ needs.linux.outputs.changed == 'true' }}
  #     uses: prantlf/unshelve-changes-action@v2
  #     with:
  #       files: ${{ needs.linux.outputs.changed-files }}
  #       discard-shelf: false
  #   - name: Build
  #     run: cmd /c make.bat
  #   - name: Shelve output
  #     if: ${{ needs.linux.outputs.changed == 'true' }}
  #     uses: prantlf/shelve-output-action@v3

  release:
    if: ${{ github.ref_name == 'master' && needs.linux.outputs.changed == 'true' }}
    needs:
      - linux
      - linux-arm
      - linux-riscv
      - macos
      - macos-arm
      - windows-cross
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/unshelve-changes-action@v2
      with:
        files: ${{ needs.linux.outputs.changed-files }}
    - uses: prantlf/unshelve-output-action@v7
    - uses: prantlf/finish-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
